version: '3.8'

# docker compose down && docker compose up -d
# http://localhost:8080/

services:

# MySQL server voor Zabbix
  zabbix-mysql-server:
    image: mysql:8.0
    container_name: zabbix-mysql-server
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    networks:
      - zabbix-net

# Zabbix server
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server-mysql
    depends_on:
      - zabbix-mysql-server
    environment:
      DB_SERVER_HOST: "zabbix-mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    ports:
      - "5000:10051"
    networks:
      - zabbix-net

# Zabbix frontend
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web-nginx-mysql
    depends_on:
      - zabbix-server-mysql
      - zabbix-mysql-server
    environment:
      ZBX_SERVER_HOST: "zabbix-server-mysql"
      DB_SERVER_HOST: "zabbix-mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

networks:
  zabbix-net:
    name: zabbix-net
