---
- name: Checkmk initiele configuratie & netwerkscan
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute Python scripts
      ansible.builtin.shell:
      # Geef configuratie mee in dit formaat: '<naam folder>:<netwerk>,<naam folder>:<netwerk>,...'
      # Voorbeeld: 'management:10.1.1.0/24,databases:10.1.2.0/24'

      # Script verantwoordelijk voor het aanmaken van folders in de checkmk inventory
        cmd: "python /home/clari-group5/scripts/inv_init.py 'Management:10.180.122.0/24,Databases:10.180.14.0/24'"

      # Script verantwoordelijk voor netwerk scans en om de checkmk folders te vullen zoals hiervoor geconfigureerd
        cmd: "python /home/clari-group5/scripts/discovery.py"